# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b22e7efed2d882721e3c61c8c014ec154790700526fcf23dba2196a460683a8d9f67e2eaaf0ad3fc6bc4eed404cb9b588d3d6782830c83462592c4de48d0c03

test:
  secret_key_base: da8fd21cbec9b64bc2344904cea2249cd81759bb59b229e7cf7294926d5daf5708478e7981beccdaf677c911942d10061905348b53c00251460cc1ed3d345f00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
